#!/bin/sh
source ./.aosbuild

aos_compiler ${CC:-clang}
aos_pkgconfig ${PKGCONF:-pkg-config}
aos_cflags -march=native -std=c11 -O3 -ffast-math -fopenmp -pipe -Wall -Wextra -Werror -pedantic
aos_lflags $CFLAGS -lm
aos_pkg sdl2 SDL2_ttf
aos_bin rastertest
aos_src src/*.c

aos_main $@
